apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ki4bxsu7b-go 
  janus-idp.io/tekton: ki4bxsu7b-go
  backstage.io/kubernetes-id: ki4bxsu7b-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ki4bxsu7b-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml